### ISSUE TITLE
Provision errors for options 2 and 6

### ISSUE THREAD

**Issue by dbrtly** [Azure-Samples/power-bi-embedded-integrate-report-into-web-app#13]
There is a possibility that the provision app in the sample is broken.
It worked fine for me all last week and now not.

option 2 throws an error:
"Oops, something broke: value cannot be null.
Parameter name: clientid"

Option 6 (the one I need) doesn't want to work. 
no response for a minute or so then error message:

"Ooops, something broke: A task was cancelled."

Maybe it's just me. Maybe not.

**Comment by ThomasDay** [comment]
I believe things time out in about 90 secs.  I have a fix for that (sets to an hour) but am not familiar with how to create a branch for review.

Also, on the clientid, make sure your visual studio is logged in to your microsoft account...if not, the clientid is null.  I know, that seems strange.

**Comment by wbreza** [comment]
Did you pull the latest change to the tool?  Power BI Embedded went GA last week and we have published updates to both the underlying REST services, SDKs and samples.

Regarding option 2 - We also have shipped with SDKs within the Azure SDK (Both powershell and xplat cli tool) that allows you to manage Power BI Embedded workspace collections.

In addition to this provision sample we have also released a [Node CLI](https://github.com/Microsoft/PowerBI-Cli) tools that is useful.

**Comment by wbreza** [comment]
The default timeout for import has been increased to work better with large PBIX files.

**Comment by ThomasDay** [comment]
Hi Wallace--I upgraded my internet to 100/100 awhile back and it's all
working like a charm with that speed.  The default timing increase will be
helpful nonetheless as a general rule or when I'm working at a remote
office without that speed.  Thanks!  The uploader is fabulous.  Tom

**Comment by wbreza** [comment]
@ThomasDay - We also recently released a new more feature rich cross platform CLI tool.  Check it out @ https://github.com/Microsoft/PowerBI-Cli.

**Comment by ThomasDay** [comment]
Hey Wallace--since you are deep in the azure embedding, can I ask you to take a peek at this [thread I just started on the forum](https://community.powerbi.com/t5/Developer/embedded-expiration-timeout-issue/m-p/59156#M1872).  I'm getting what seem like time out errors that are very unruly and I don't know what to look for here.  The token timeout has been set to 1 hr, btw.  Thanks...hope this isn't an out-of-range question for you and thanks in advance, Tom

**Comment by ThomasDay** [comment]
Hello Wallace...Tom Day here.
I posted a reply to our thread on the 403 errors we're getting on our
powerbi embedded site.  I also have a reasonably small model that fails
readily when we embed it.  I'd like to get it to you directly rather than
through a posting on the forum if you don't mind.  I can also share a link
to our site where it's embedded so you can see the failure first hand if
that is useful to you.
Let me know how to get it to you, please and thanks!
Tom
781-254-4157 (c)

**Comment by wbreza** [comment]
@ThomasDay - I saw something similar today with one of my own models.  Feel free to email me at wabreza at microsoft dot com.

**Comment by ThomasDay** [comment]
I've tried to send you an email with a link to our model on dropbox and
each attempt has been rejected when sent to that address.

**Comment by wbreza** [comment]
Sorry - My email was incorrect above.  It's wabreza at microsoft dot com.

**Comment by mattmazzola** [comment]
This was resolved offline. If I recall, it was related to improperly issuing tokens with lifespan of minutes instead of hours. The 403 errors were from requests using the token even after it has expired. The fix was to properly issue tokens with sufficient lifespan for normal use duration.
