### ISSUE TITLE
Updating existing workspaces with a new pbix file

### ISSUE THREAD

**Issue by dbrtly** [Azure-Samples/power-bi-embedded-integrate-report-into-web-app#22]
I'm sure smarter people than me could modify the app, but I don't have that skill.

Manually retrieving the current uniqueidentifier, deleting it and then quickly uploading a new file with the same name is a rather inelegant solution.

Surely the Import PBIX Desktop file into an existing workspace could be modified to detect when the workspace has an existing file and give the user the option of seamlessly updating.

**Comment by wbreza** [comment]
Are you referring the the "overwrite" bug on the `import` API?  If not - can you clarify your question?

**Comment by dbrtly** [comment]
I have a report 'a' in workspace 1.I make changes to report a in PBI Desktop. I want update the file I the workspace. 
The ProvisionSample app doesn't have a built feature for updates. I have to get the GUID for report a, type it out in notepadThen delete report a from the workspace and hope no user notices, then upload the new version of report a. It's clunky. 
Maybe you didn't develop the provision sample with an expectation that someone would use it who didn't know how to write a better update function. I unfortunately don't have that skill but want to use PBI embedded. 
Thanks,
Daniel

On Fri, Aug 26, 2016 at 5:31 PM +1000, "Wallace Breza" notifications@github.com wrote:

Are you referring the the "overwrite" bug on the import API?  If not - can you clarify your question?

**Comment by wbreza** [comment]
This sample was never intended to be an end all production solution.  It was created to be a basic example of the types of features available.  

We have a cross platform CLI tool that may be more useful for you needs. You can find out more at our git repo @ https://github.com/Microsoft/PowerBI-cli.  It will allow you to quick re-import a PBIX file and replace a report/dataset with the same name using the `--overwrite` flag.

There is currently a bug in the backend API which will be fixed in production next week around 8/31 which should make this a good end to end scenario for you.

Example:

```
$ powerbi import --help

  Usage: cli-import [options]

  Options:

    -h, --help                       output usage information
    -V, --version                    output the version number
    -c, --collection <collection>    The Power BI workspace collection
    -w, --workspace <workspaceId>    The Power BI workspace
    -k, --accessKey <accessKey>      The Power BI workspace collection access key
    -n, --displayName <displayName>  The dataset display name
    -f, --file <file>                The PBIX file to upload
    -o, --overwrite [overwrite]      Whether to overwrite a dataset with the same name.  Default is false
    -b --baseUri [baseUri]           The base uri to connect to

  Examples:

    $ powerbi import -c <collection> -k <accessKey> -w <workspace> -f <file> -n <displayName>
```

Hope this helps.
